const cars = [
  {
    id: 1,
    title: 'Alfa Romeo',
    country: 'Italy',
    img: 'https://www.finansajans.com/images/haberler/2020/07/alfa-romeo.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 2,
    title: 'Audi',
    country: 'Germany',
    img: 'https://i.ytimg.com/vi/L42-aFe8bMo/maxresdefault.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 3,
    title: 'BMW',
    country: 'Germany',
    img: 'https://cdn.motor1.com/images/mgl/vEJmQ/s1/bmw-i8-m-rendering.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 4,
    title: 'Chevrolet',
    country: 'America',
    img: 'https://cdn.motor1.com/images/mgl/jGwEy/s1/4x3/2020-chevrolet-camaro-lt1.webp',
    category: 'SuperFastCar',
  },
  {
    id: 5,
    title: 'Dacia',
    country: 'Italy',
    img: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/2021_Dacia_Sandero_Stepway_Prestige_TCE_1.0_Front.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 6,
    title: 'Daihatsu',
    country: 'Italy',
    img: 'https://cdn.motor1.com/images/mgl/2RyMk/s3/2019-daihatsu-wakuwaku-concept.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 7,
    title: 'Ferrari',
    country: 'Italy',
    img: 'https://www.carscoops.com/wp-content/uploads/2021/07/Ferrari-F8-Tributo-2a.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 8,
    title: 'Ford',
    country: 'America',
    img: 'https://www.webtekno.com/images/editor/default/0003/10/262a7cba04c79db78b97ae23e1faa45eb2d064f0.jpeg',
    category: 'SuperFastCar',
  },
  {
    id: 9,
    title: 'Fiat',
    country: 'Italy',
    img: 'https://otomobil.fiat.com.tr/content/dam/fiat/cross/new_family_page/500l/Trim/fiat-500L-mirror-blue-familycar-02-desktop-606x340.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 10,
    title: 'Honda',
    country: 'Japan',
    img: 'https://cdn.motor1.com/images/mgl/RzE0m/s1/2020-honda-civic-hatchback-facelift.webp',
    category: 'SuperFastCar',
  },
  {
    id: 11,
    title: 'Hyundai',
    country: 'Korea',
    img: 'https://www.hyundai.com/content/dam/hyundai/tr/tr/images/home/Nisan-2021/tucson-2021/one-cikanlar-1.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 12,
    title: 'Jaguar',
    country: 'England',
    img: 'https://i0.wp.com/goflatoutph.com/wp-content/uploads/2020/09/F-TYPE-b.jpg?resize=1440%2C580&ssl=1',
    category: 'SuperFastCar',
  },
  {
    id: 13,
    title: 'Jeep',
    country: 'America',
    img: 'https://www.challenge.ma/wp-content/uploads/2020/12/64-71-6.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 14,
    title: 'Kia',
    country: 'Korea',
    img: 'https://cdn.motor1.com/images/mgl/m7k2v/s1/2022-kia-sportage.webp',
    category: 'SuperFastCar',
  },
  {
    id: 15,
    title: 'Lamborghini',
    country: 'Italy',
    img: 'https://devirsaati.com/wp-content/uploads/2020/07/lamborghini_Sian_Roadster__4_.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 16,
    title: 'Land Rover',
    country: 'England',
    img: 'https://otomobilkampanyalar.com/wp-content/uploads/2021/10/land-rover-modelleri.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 17,
    title: 'Mazda',
    country: 'Japan',
    img: 'https://cdn.motor1.com/images/mgl/GGxGG/s1/2021-mazda6-carbon-edition.webp',
    category: 'SuperFastCar',
  },
  {
    id: 18,
    title: 'Mercedes-Benz',
    country: 'Germany',
    img: 'https://cdn.carbuzz.com/gallery-images/840x560/859000/200/859225.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 19,
    title: 'Mini',
    country: 'England',
    img: 'https://www.kosifleroto.com.tr/MiniYeni/Contents/images/TumModeller/Mini3Kapi/mini3kapi.png',
    category: 'SuperFastCar',
  },
  {
    id: 20,
    title: 'Mitsubishi',
    country: 'Japan',
    img: 'https://hips.hearstapps.com/autoweek/assets/s3fs-public/2015_lancer_evolution_fe_23.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 21,
    title: 'Nissan',
    country: 'Japan',
    img: 'https://cdn.motor1.com/images/mgl/8LAjo/s1/2020-nissan-gt-r-nismo.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 22,
    title: 'Opel',
    country: 'Germany',
    img: 'https://www.auto-data.net/images/f43/Opel-Astra-L-Sports-Tourer.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 23,
    title: 'Peugeot',
    country: 'France',
    img: 'https://cdn.motor1.com/images/mgl/KP8JQ/s1/peugeot-308-2021.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 24,
    title: 'Porsche',
    country: 'Germany',
    img: 'https://www.sifiraracal.com/resim/haber/8264/iste-yeni-cayman--porsche-cayman-gt4-rs-2.png',
    category: 'SuperFastCar',
  },
  {
    id: 25,
    title: 'Renault',
    country: 'France',
    img: 'https://images.caradisiac.com/images/3/8/8/1/183881/S0-renault-talisman-restylee-2020-prix-a-partir-de-33-400-eur-633717.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 26,
    title: 'Seat',
    country: 'Spain',
    img: 'https://arabam-blog.mncdn.com/wp-content/uploads/2021/01/2020-seat-leon-7-1280x720-1.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 27,
    title: 'Subaru',
    country: 'Japan',
    img: 'https://cdn.motor1.com/images/mgl/koY8jM/s1/subaru-wrx-s4-sti-performance-concept.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 28,
    title: 'Suzuki',
    country: 'Japan',
    img: 'https://arbstorage.mncdn.com/modelphotos/1cea0060-a878-416c-b490-0469554f5e2a_912x513.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 29,
    title: 'Tata',
    country: 'India',
    img: 'https://www.financialexpress.com/wp-content/uploads/2021/10/Tata-Punch-SUV-1.jpg',
    category: 'SuperFastCar',
  },
  {
    id: 30,
    title: 'Toyota',
    country: 'Japan',
    img: 'https://cdn.motor1.com/images/mgl/Q1LGY/s1/toyota-bz4x-concept-rear-angle.webp',
    category: 'SuperFastCar',
  },
  {
    id: 31,
    title: 'Volkswagen',
    country: 'Germany',
    img: 'https://tugrulkatkak.files.wordpress.com/2019/11/vw_arteon_img-4699_800x450.jpg?w=799&h=450',
    category: 'SuperFastCar',
  },
  {
    id: 32,
    title: 'Volvo',
    country: 'Sweeden',
    img: 'https://media.autoexpress.co.uk/image/upload/s--X-WVjvBW--/f_auto,t_content-image-full-desktop@1/v1583150113/autoexpress/2020/03/Volvo%20XC90%20UK%20review%20-%201%20.jpg',
    category: 'SuperFastCar',
  },
];
